ADDED: player creation depending on clients
iDommel/RType pull request #16
Opened 2022-10-24 13:50 UTC by MauxC

2022-10-24 13:57 UTC, Varriss submitted a review, later dismissed

2022-10-24 14:27 UTC, iDommel requested changes
Briefs

2022-10-24 14:27 UTC, iDommel commented on src/IScene.hpp
> +        virtual void setAddEntityCallback(std::function<void(std::shared_ptr<IEntity>, SceneType)> callback) = 0;
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/Scene.cpp
> +    Scene::Scene(std::function<std::unique_ptr<IScene>()> init, SceneType scene) : _initFunc(init), _type(scene)
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/Scene.hpp
> +        Scene(std::function<std::unique_ptr<IScene>()> init, SceneType type);
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/Scene.hpp
> +        void setAddEntityCallback(std::function<void(std::shared_ptr<IEntity>, SceneType)> callback);
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/SceneManager.cpp
> +    void SceneManager::setAddEntityCallback(std::function<void(std::shared_ptr<IEntity>, SceneType)> callback)
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/ANetworkSystem.hpp
> +        void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene);
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/AudioSystem.hpp
> +        void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene) final;
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/CollideSystem.hpp
> +        void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene) final;
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/EventSystem.hpp
> +        void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene) final;
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/GameSystem.hpp
> +        void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene) final;
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/GraphicSystem.cpp
> +    void GraphicSystem::onEntityAdded(std::shared_ptr<IEntity> entity, SceneType)
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/GraphicSystem.hpp
> +        void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene) final;
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/ISystem.hpp
> +        virtual void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene) = 0;
Missing brief

2022-10-24 14:27 UTC, iDommel commented on src/systems/ParticlesSystem.hpp
> +        void onEntityAdded(std::shared_ptr<IEntity> entity, SceneType scene) final;
Missing brief

2022-10-30 09:37 UTC, Varriss commented on src/IScene.hpp
>           */
scene type param missing in doxygen

2022-10-30 09:42 UTC, Varriss commented on src/systems/ANetworkSystem.cpp
> +        _serverAddr = QHostAddress(QStringLiteral("10.42.0.1"));
Should we make a Define for the host address ?

2022-10-30 09:46 UTC, Varriss commented on src/systems/NetworkServerSystem.hpp
> +        void writeToClient(const std::string &msg, std::pair<QString /*addr*/, unsigned short /*port*/> client);
comments inside function declaration

2022-10-30 09:47 UTC, Varriss submitted a review, later dismissed

2022-10-31 09:38 UTC, MauxC commented on src/IScene.hpp
>           */
It's wrong !!

2022-10-31 10:43 UTC, MauxC commented on src/IScene.hpp
>           */
It's wrong !!

2022-10-31 10:46 UTC, merged